!jmb-configuration-v1

name: JMB
outboundEndpoints:
- name: notRouted
  flow:
    name: nullOutboundFlow          
- name: WMA
  flow:
    name: fileOutboundFlow
    parameters:
    - name: "path"
      value: "./outbound/test-output-wma"
    - name: "fileName"
      value: "outputMessageWMA.xml"
- name: TMA
  flow:
    name: fileOutboundFlow
    parameters:
    - name: "path"
      value: "./outbound/test-output-tma"
    - name: "fileName"
      value: "outputMessageTMA.json"
- name: ACK.GLOBAL
  flow:
    name: fileOutboundFlow
    parameters:
    - name: "path"
      value: "./outbound/ack"
    - name: "fileName"
      value: "ack.json"
- name: LOC.DC0001
  flow:
    name: fileOutboundFlow
    parameters:
    - name: "path"
      value: "./outbound/ack"
    - name: "fileName"
      value: "ack-error.json"
- name: MB-LDE
  flow:
    name: jmsOutboundFlow
    parameters:
    - name: "queue"
      value: "MB-LDE"
      
- name: MB-LP
  flow:
    name: jmsOutboundFlow
    parameters:
    - name: "queue"
      value: "LPA_INBOUND_QUEUE"
- name: MB-SCPO
  flow:
    name: jmsOutboundFlow
    parameters:
    - name: "queue"
      value: "MB-SCPO"      
outboundMappings:
  - receiver: 'WMA.WEST|WMA.EAST'
    request: '*:*:*'
    outboundEndpoint: 'WMA'
  - receiver: 'TMA.WEST|TMA.EAST'
    request: '*:*:*'
    outboundEndpoint: 'TMA'
  - receiver: 'LOC.DC0001'
    request: '*:*:*'
    outboundEndpoint: 'LOC.DC0001'
  - receiver: 'NOT.ROUTED'
    request: '*:*:*'
    outboundEndpoint: 'notRouted'
  - receiver: 'LDE.GLOBAL'
    request: '*:*:*'
    outboundEndpoint: 'MB-LDE'
  - receiver: 'LP.GLOBAL'
    request: '*:*:*'
    outboundEndpoint: 'MB-LP'
  - receiver: 'SCPO.GLOBAL'
    request: '*:*:*'
    outboundEndpoint: 'MB-SCPO'